import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Menu() {
  return (
    <div>
      <h1>Menu</h1>
    </div>
  );
}
